## [作業重點]
使用 Sklearn 中的 Lasso, Ridge 模型，來訓練各種資料集，務必了解送進去模型訓練的**資料型態**為何，也請了解模型中各項參數的意義。

機器學習的模型非常多種，但要訓練的資料多半有固定的格式，確保你了解訓練資料的格式為何，這樣在應用新模型時，就能夠最快的上手開始訓練！

## 練習時間
試著使用 sklearn datasets 的其他資料集 (boston, ...)，來訓練自己的線性迴歸模型，並加上適當的正則化來觀察訓練情形。

## Linear Regression - Boston

In [124]:
import numpy as np
import matplotlib as plt
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [125]:
# 讀取 boston 房價資料集
boston = datasets.load_boston()
# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(boston.data, boston.target, test_size=0.2, random_state=4)
# 建立一個線性回歸模型
regr = linear_model.LinearRegression()
# 將訓練資料丟進去模型訓練
regr.fit(x_train, y_train)
# 將測試資料丟進模型得到預測結果
y_pred = regr.predict(x_test)

In [126]:
# 預測值與實際值的差距，使用 MSE
print(regr.coef_)

[-1.15966452e-01  4.71249231e-02  8.25980146e-03  3.23404531e+00
 -1.66865890e+01  3.88410651e+00 -1.08974442e-02 -1.54129540e+00
  2.93208309e-01 -1.34059383e-02 -9.06296429e-01  8.80823439e-03
 -4.57723846e-01]


In [127]:
print("Mean squared error: %.2f" %mean_squared_error(y_test, y_pred))

Mean squared error: 25.42


## Lasso - Boston

In [128]:
# 讀取 boston 房價資料集
boston = datasets.load_boston()
# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(boston.data, boston.target, test_size=0.2, random_state=4)
# 建立一個線性回歸模型
lasso = linear_model.Lasso(alpha=1.0)
# 將訓練資料丟進去模型訓練
lasso.fit(x_train, y_train)
# 將測試資料丟進模型得到預測結果
y_pred = lasso.predict(x_test)

In [129]:
# 印出各特徵對應的係數
lasso.coef_

array([-0.06494981,  0.04581458, -0.        ,  0.        , -0.        ,
        1.18140024,  0.01109101, -0.73695809,  0.23350042, -0.01551065,
       -0.69270805,  0.00763157, -0.6927848 ])

In [130]:
# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f" %mean_squared_error(y_test, y_pred))

Mean squared error: 28.95


## Ridge - Boston

In [131]:
# 讀取 boston 房價資料集
boston = datasets.load_boston()
# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(boston.data, boston.target, test_size=0.2, random_state=4)
# 建立一個線性回歸模型
ridge = linear_model.Ridge(alpha=0.5)
# 將訓練資料丟進去模型訓練
ridge.fit(x_train, y_train)
# 將測試資料丟進模型得到預測結果
y_pred = ridge.predict(x_test)

In [132]:
# 印出各特徵對應的係數
ridge.coef_

array([-1.13720313e-01,  4.76370805e-02, -1.25294762e-02,  3.07531514e+00,
       -1.19789169e+01,  3.91845004e+00, -1.51046851e-02, -1.47224633e+00,
        2.81475089e-01, -1.37075697e-02, -8.57737917e-01,  9.03172343e-03,
       -4.62924119e-01])

In [133]:
# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f" %mean_squared_error(y_test, y_pred))

Mean squared error: 25.60


## Linear Regression - Linnerud

In [134]:
# 讀取 boston 房價資料集
linnerud = datasets.load_linnerud()
# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(linnerud.data, linnerud.target, test_size=0.2, random_state=4)
# 建立一個線性回歸模型
regr = linear_model.LinearRegression()
# 將訓練資料丟進去模型訓練
regr.fit(x_train, y_train)
# 將測試資料丟進模型得到預測結果
y_pred = regr.predict(x_test)

In [135]:
print(regr.coef_)

[[-1.28756417 -0.18005567  0.0724611 ]
 [-0.23553638 -0.03945105  0.03009547]
 [ 0.17356644  0.05247911 -0.03166777]]


In [136]:
# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f" %mean_squared_error(y_test, y_pred))

Mean squared error: 386.15


## Lasso- Linnerud

In [137]:
# 讀取 boston 房價資料集
linnerud = datasets.load_linnerud()
# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(linnerud.data, linnerud.target, test_size=0.2, random_state=4)
# 建立一個線性回歸模型
lasso = linear_model.Lasso(alpha=1)
# 將訓練資料丟進去模型訓練
lasso.fit(x_train, y_train)
# 將測試資料丟進模型得到預測結果
y_pred = lasso.predict(x_test)

In [138]:
print(lasso.coef_)

[[-1.21702413 -0.18301572  0.07085454]
 [-0.16500267 -0.04240416  0.02848377]
 [ 0.10302969  0.05543243 -0.03005608]]


In [139]:
# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f" %mean_squared_error(y_test, y_pred))

Mean squared error: 382.88


## Ridge - Linnerud

In [150]:
# 讀取 boston 房價資料集
linnerud = datasets.load_linnerud()
# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(linnerud.data, linnerud.target, test_size=0.2, random_state=4)
# 建立一個線性回歸模型
ridge = linear_model.Ridge(alpha=3.0)
# 將訓練資料丟進去模型訓練
ridge.fit(x_train, y_train)
# 將測試資料丟進模型得到預測結果
y_pred = ridge.predict(x_test)

In [151]:
print(ridge.coef_)

[[-1.27010306 -0.180972    0.07228818]
 [-0.23234496 -0.0396168   0.03006142]
 [ 0.17123071  0.05259769 -0.03164009]]


In [152]:
# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f" %mean_squared_error(y_test, y_pred))

Mean squared error: 385.50
